config/routes.rb
Rails.application.routes.draw do

  root "static_pages#root"

  resources :poems
  resources :journals
  resources :submissions do
    get 'acceptance', on: :member
  end
  resources :notes, only: [:create, :destroy]
end

app/models/journal.rb
class Journal < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true

  has_many :submissions, dependent: :destroy
  has_many :notes, as: :notable

end

app/models/note.rb
class Note < ActiveRecord::Base

  validates :body, :notable_id, :notable_type, presence: true

  belongs_to :notable, polymorphic: true

end

app/models/poem.rb
class Poem < ActiveRecord::Base

  validates :title, :status, :written_on, presence: true
  validates :status, inclusion: ["NONE", "SUBMITTED", "PUBLISHED"]

  has_many :submission_poems, dependent: :destroy
  has_many :submissions, through: :submission_poems, source: :submission
  has_many :notes, as: :notable

end

app/models/submission.rb
class Submission < ActiveRecord::Base

  validates :journal_id, :date_made, presence: true

  belongs_to :journal
  has_many :submission_poems, inverse_of: :submission, dependent: :destroy
  has_many :poems, through: :submission_poems, source: :poem
  has_many :notes, as: :notable

  after_create :set_poem_status_to_submitted
  after_update :reset_poem_status, if: :rejected?
  after_update :adjust_poem_status, if: :accepted?

  attr_accessor :accepted_poem_ids

  def set_poem_status_to_submitted
    self.poems.update_all(status: "SUBMITTED")
  end

  def rejected?
    self.result_changed? && self.result == "REJECTION"
  end

  def accepted?
    self.result_changed? && self.result == "ACCEPTANCE"
  end

  def reset_poem_status
    self.poems.includes(:submissions).each do |poem|
      if poem.submissions.where("submissions.result = 'PENDING' OR submissions.result = 'ACCEPTED'").count == 0
        poem.update(status: "NONE")
      end
    end
  end

  def adjust_poem_status
    self.poems.includes(:submissions).each do |poem|
      if accepted_poem_ids.include?(poem.id.to_s)
        poem.update(status: "PUBLISHED")
      else
        if poem.submissions.where("submissions.result = 'PENDING'").count == 0
          poem.update(status: "NONE")
        end
      end
    end
  end

end

app/models/submission_poem.rb
class SubmissionPoem < ActiveRecord::Base

  validates :submission, :poem_id, presence: true
  validates :submission_id, uniqueness: { scope: :poem_id }

  belongs_to :submission, inverse_of: :submission_poems
  belongs_to :poem

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController

  def index
    @journals = Journal.all
    render :index
  end

  def show
    @journal = Journal.includes(submissions: :poems,).find(params[:id])
    render :show
  end

  def new
    @journal = Journal.new
    render :new
  end

  def create
    @journal = Journal.new(journal_params)
    if @journal.save
      redirect_to journals_url
    else
      flash[:now] = @journal.errors.full_messages
    end
  end

  def edit
    @journal = Journal.find(params[:id])
    render :edit
  end

  def update
    @journal = Journal.find(params[:id])
    if @journal.update(journal_params)
      redirect_to journals_url
    else
      flash[:now] = @journal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @journal = Journal.find(params[:id])
    @journal.destroy
    redirect_to journals_url
  end

  private

  def journal_params
    params.require(:journal).permit(:name, :email, :url, :address, :simul_submit, :phone_number)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to url_for(@note.notable)
    else
      flash[notices] << @note.errors.full_messages
      redirect_to url_for(@note.notable)
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @notable = @note.notable
    @note.destroy
    redirect_to url_for(@notable)
  end

  private

  def note_params
    params.require(:note).permit(:body, :notable_type, :notable_id)
  end

end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController

  def index
    @poems = Poem.all
    render :index
  end

  def show
    @poem = Poem.includes(submissions: :journal).find(params[:id])
    render :show
  end

  def new
    @poem = Poem.new
    render :new
  end

  def create
    @poem = Poem.new(poem_params)
    if @poem.save
      redirect_to poem_url(@poem)
    else
      flash[:now] = @poem.errors.full_messages
      render :new
    end
  end

  def edit
    @poem = Poem.find(params[:id])
    render :edit
  end

  def update
    @poem = Poem.find(params[:id])
    if @poem.update(poem_params)
      redirect_to poem_url(@poem)
    else
      flash[:now] = @poem.errors.full_messages
      render :edit
    end
  end

  def destroy
    @poem = Poem.find(params[:id])
    @poem.destroy
    redirect_to poems_url
  end

private

def poem_params
  params.require(:poem).permit(:title, :written_on)
end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def root
    render :root
  end

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  def index
    @submissions = Submission.includes(:journal).all
    render :index
  end

  def show
    @submission = Submission.find(params[:id])
    render :show
  end

  def new
    @journals = Journal.all
    @poems = Poem.all
    @submission = Submission.new
    render :new
  end

  def create
    @submission = Submission.new(submission_params)
    @submission.date_made = Time.now
    if @submission.save
      redirect_to submissions_url
    else
      flash[:now] = @submission.errors.full_messages
      render :new
    end
  end

  def edit
    @journals = Journal.all
    @poems = Poem.all
    @submission = Submission.includes(:journal, :poems).find(params[:id])
    render :edit
  end

  def update
    @submission = Submission.find(params[:id])

    if @submission.update(submission_params)
      redirect_to submissions_url
    else
      flash[:now] = @submission.errors.full_messages
      render :edit
    end
  end

  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy
    redirect_to submissions_url
  end

  def acceptance
    @submission = Submission.includes(:poems).find(params[:id])
    render :acceptance
  end

  private

  def submission_params
    params.require(:submission).permit(:journal_id, :result, poem_ids: [], accepted_poem_ids: [])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def hidden_token
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
  end

end

app/views/journals/_form.html.erb
<% button_text = journal.persisted? ? "Update Journal" : "Add Journal" %>
<% form_action = journal.persisted? ? journal_url(journal) : journals_url %>
<% hidden_input = journal.persisted? ? "<input type='hidden' name='_method' value='PATCH'>".html_safe : "" %>

<form action="<%= form_action %>" method="post">

  <label for="journal_name">Name:</label>
  <input type="text" id="journal_name" name="journal[name]" value="<%= journal.name %>">
  <br>
  <br>

  <label for="journal_url">URL:</label>
  <input type="text" id="journal_url" value="<%= journal.url %>" name="journal[url]">
  <br>
  <br>

  <label for="journal_email">email:</label>
  <input type="text" id="journal_email" value="<%= journal.email %>" name="journal[email]">
  <br>
  <br>

  <label for="journal_phone_number">phone:</label>
  <input type="text" id="journal_phone_number" value="<%= journal.phone_number %>" name="journal[phone_number]">
  <br>
  <br>

  <label for="journal_address">Address:</label>
  <textarea name="journal[address]" id="journal_address"><%= journal.address %></textarea>
    <br>
    <br>

  <label for "journal_simul_submit_allowed">Simultaneous Submission Allowed:</label>
  <input type="radio"
         name="journal[simul_submit]"
         id="journal_simul_submit"
         value="true">
  <br>
  <label for "journal_simul_submit_not_allowed">Simultaneous Submission Not Allowed</label>
  <input type="radio"
  name="journal[simul_submit]"
  id="journal_simul_submit_not_allowed"
  value="false">
  <br>
  <br>

  <%= hidden_token %>
  <%= hidden_input %>

  <input type="submit" value="<%= button_text %>">
  <br>
  <br>
</form>

app/views/journals/edit.html.erb
<h1>Edit <%= @journal.name %></h1>

<%= render 'journals/form', journal: @journal %>

<a href="<%= journals_url %>">Back!</a>

app/views/journals/index.html.erb
<h1>All your Journals!</h1>

<a href="<%= new_journal_url %>">New Journal!</a>

<ul>
  <% @journals.each do |journal|  %>
  <a href="<%= journal_url(journal)%>"><%= journal.name %></a>
  <a href="<%= edit_journal_url(journal) %>">Edit</a>
  <form action="<%= journal_url(journal) %>" method="post">
    <%= hidden_token %>
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete!">
  </form>
  <% end %>
</ul>

<a href="<%= root_url %>">Back!</a>

app/views/journals/new.html.erb
<h1>Add New Journal!</h1>

<%= render 'journals/form', journal: @journal %>

<a href="<%= journals_url %>">Back!</a>

app/views/journals/show.html.erb
<h1><%= @journal.name %></h1>

<table>
  <tr>
    <th>name</th>
    <td><%= @journal.name %></td>
  </tr>
  <tr>
    <th>email</th>
    <td><%= @journal.email %></td>
  </tr>
  <tr>
    <th>phone number</th>
    <td><%= @journal.phone_number %></td>
  </tr>
  <tr>
    <th>url</th>
    <td><%= @journal.url %></td>
  </tr>
  <tr>
    <th>address</th>
    <td><%= @journal.address %></td>
  </tr>
  <tr>
    <th>simultaneous submiission</th>
    <td><%= @journal.simul_submit %></td>
  </tr>
</table>

<h2>Submitted Poems</h2>
<% @journal.submissions.each do |submission| %>
  <h3><%= submission.date_made %></h3>
  <ul>
    <% submission.poems.each do |poem| %>
      <li><%= poem.title %></li>
    <% end %>
  </ul>
<% end %>


<%= render 'notes/note', notes: @journal.notes, notable_type: "Journal", notable_id: @journal.id %>

<a href="<%= journals_url %>">Back</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SubMitten</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_note.html.erb
<h3>Notes</h3>
<ul>
  <% notes.each do |note| %>
    <li>
      <%= note.body %>
      <form action="<%= note_url(note) %>" method="POST">
        <%= hidden_token %>
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Delete Note">
      </form>
    </li>

  <% end %>
</ul>
<h3>New Note</h3>
<form action="<%= notes_url %>" method="post">
  <label for="note_body"></label>
  <textarea name="note[body]" id="note_body"></textarea>
  <input type="hidden" name="note[notable_type]" value="<%= notable_type %>">
  <input type="hidden" name="note[notable_id]" value="<%= notable_id%>">
  <%= hidden_token %>
  <input type="submit" value="Post Note">
</form>

app/views/poems/_form.html.erb
<% button_text = poem.persisted? ? "Update Poem" : "Add Poem" %>
<% form_action = poem.persisted? ? poem_url(poem) : poems_url %>
<% hidden_input = poem.persisted? ? "<input type='hidden' name='_method' value='PATCH'>".html_safe : "" %>

<form action="<%= form_action %>" method="post">

  <label for="poem_title">Title:</label>
  <input type="text" id="poem_title" name="poem[title]" value="<%= poem.title %>">

  <label for="poem_written_on">Written On:</label>
  <input type="date" id="poem_written_on" value="<%= poem.written_on %>" name="poem[written_on]">

  <%= hidden_token %>
  <%= hidden_input %>

  <input type="submit" value="<%= button_text %>">

</form>

app/views/poems/edit.html.erb
<h1>Edit this poem!</h1>

<%= render 'poems/form', poem: @poem %>

<a href="<%= poems_url %>">Back</a>

app/views/poems/index.html.erb
<h1>All your Poems!</h1>

<a href="<%= new_poem_url %>">New Poem!</a>

<ul>
<% @poems.each do |poem|  %>
  <a href="<%= poem_url(poem)%>"><%= poem.title %></a>
  <a href="<%= edit_poem_url(poem) %>">Edit</a>
  <form action="<%= poem_url(poem) %>" method="post">
    <%= hidden_token %>
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete!">
  </form>
<% end %>
</ul>

<a href="<%= root_url %>">Back!</a>

app/views/poems/new.html.erb
<h1>Add a new poem!</h1>

<%= render "poems/form",  poem: @poem  %>

<a href="<%= poems_url %>">Back</a>

app/views/poems/show.html.erb
<h1><%= @poem.title %></h1>

<table>
  <tr>
    <th>title</th>
    <td><%= @poem.title %></td>
  </tr>
  <tr>
    <th>written_on</th>
    <td><%= @poem.written_on %></td>
  </tr>
  <tr>
    <th>status:</th>
    <td><%= @poem.status %></td>
  </tr>
</table>

<h2>Submissions:</h2>
<ul>
  <% @poem.submissions.each do |submission| %>
    <li>
      <%= "#{submission.journal.name}--#{submission.date_made}" %>
    </li>
  <% end %>
</ul>

<%= render 'notes/note', notes: @poem.notes, notable_type: "Poem", notable_id: @poem.id %>

<a href="<%= poems_url %>">Back</a>

app/views/static_pages/root.html.erb
<h1>SubMitten</h1>

<nav>
  <ul>

    <li><a href="<%= poems_url %>">Poems</a></li>
    <li><a href="<%= journals_url %>">Journals</a></li>
    <li><a href="<%= submissions_url %>">Submissions</a></li>

  </ul>
</nav>

app/views/submissions/_form.html.erb
<% button_text = submission.persisted? ? "Update Submission" : "Create Submission" %>
<% form_action = submission.persisted? ? submission_url(submission) : submissions_url %>
<% hidden_input = submission.persisted? ? "<input type='hidden' name='_method' value='PATCH'>".html_safe : "" %>

<form action="<%= form_action %>" method="post">

  <label for="submission_journal_id">Journal:</label>
  <select id="submissions_journal_id"
          name="submission[journal_id]">
    <% journals.each do |journal| %>
      <option value="<%= journal.id %>"
              <%= "selected" if submission.journal == journal %>>
        <%= journal.name %>
      </option>
    <% end %>
  </select>

  <br>
  <br>
  <label>Poems</label>
  <br>
  <% poems.each do |poem| %>
    <label id="submission_poem_id_<%=poem.id%>">
      <%= poem.title %>
    </label>
    <input type="checkbox"
           name="submission[poem_ids][]"
           value="<%= poem.id %>"
           id="submission_poem_id_<%=poem.id%>"
           <%= "checked" if submission.poems.include?(poem) %>>
    <br>
  <% end %>
  <%= hidden_token %>
  <%= hidden_input %>

  <input type="submit" value="<%= button_text %>">

</form>

app/views/submissions/acceptance.html.erb
<h1>Congratulations!!!!!</h1>

<h2>Which Poems were picked up?</h2>

<form action="<%= submission_url(@submission) %>" method="POST">
<% @submission.poems.each do |poem| %>
  <label id="submission_accepted_poem_id_<%=poem.id%>">
    <%= poem.title %>
  </label>
  <input type="checkbox"
         name="submission[accepted_poem_ids][]"
         value="<%= poem.id %>"
         id="submission_accepted_poem_id_<%=poem.id%>">
  <br>
<% end %>
<input type="hidden" name="submission[result]" value="ACCEPTANCE">
<%= hidden_token %>
<input type="hidden" name="_method" value="PATCH">
<input type="submit" value="Post Acceptances!">

app/views/submissions/edit.html.erb
<h1>Edit Submission</h1>

<%= render 'submissions/form', submission: @submission, journals: @journals, poems: @poems %>

<a href="<%= submissions_url %>">Back!</a>

app/views/submissions/index.html.erb
<h1>All your Submissions!</h1>

<a href="<%= new_submission_url %>">New Submission!</a>

<ul>
  <% @submissions.each do |submission|  %>
  <a href="<%= submission_url(submission)%>">
    <%= submission.journal.name %>--<%= submission.created_at %>
  </a>
  <a href="<%= edit_submission_url(submission) %>">Edit</a>
  <form action="<%= submission_url(submission) %>" method="post">
    <%= hidden_token %>
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete!">
  </form>
  <% end %>
</ul>

<a href="<%= root_url %>">Back!</a>

app/views/submissions/new.html.erb
<h1>New Submission!</h1>

<%= render 'submissions/form', submission: @submission, journals: @journals, poems: @poems %>

<a href="<%= submissions_url %>">Back</a>

app/views/submissions/show.html.erb
<h1><%= "#{@submission.journal.name}--#{@submission.date_made}" %></h1>

<h2>Result: <%= @submission.result %></h2>

<ul>
  <% @submission.poems.each do |poem| %>
    <li><%= poem.title %></li>
  <% end %>
</ul>

<% if @submission.result == "PENDING" %>

  <h2>Result?</h2>
  <form action="<%= submission_url(@submission) %>" method="POST">
    <%= hidden_token %>
    <input type="hidden" name="submission[result]" value="REJECTION">
    <input type="hidden" name="_method" value="PATCH">
    <input type="submit" value="Rejection">
  </form>
  <br>
  <a href="<%= acceptance_submission_url(@submission) %>">Acceptance</a>
<% end %>

<%= render 'notes/note', notes: @submission.notes, notable_type: "Submission", notable_id: @submission.id %>

<a href="<%= submissions_url %>">Back!</a>